# Generated by Django 5.1.1 on 2024-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('telegram_token', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('chat_id', models.CharField(max_length=200)),
                ('bot', models.ManyToManyField(related_name='chat', to='telebot.botsetting')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('message_text', models.TextField()),
                ('bot', models.ManyToManyField(related_name='message', to='telebot.botsetting')),
            ],
        ),
    ]
