# Generated by Django 5.1.1 on 2024-10-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsetting',
            options={'ordering': ['id'], 'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='chatsetting',
            options={'ordering': ['id'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='messagesetting',
            options={'ordering': ['id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
