# Generated by Django 5.1.1 on 2024-10-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_alter_botsetting_options_alter_chatsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsetting',
            name='bot',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat', to='telebot.botsetting'),
        ),
        migrations.AlterField(
            model_name='messagesetting',
            name='bot',
            field=models.ManyToManyField(blank=True, null=True, related_name='message', to='telebot.botsetting'),
        ),
    ]
