# Generated by Django 5.1.1 on 2024-10-15 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_alter_chatsetting_bot_alter_messagesetting_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsetting',
            name='bot',
        ),
        migrations.AddField(
            model_name='messagesetting',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='telebot.chatsetting'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='messagesetting',
            name='bot',
        ),
        migrations.AddField(
            model_name='messagesetting',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='telebot.botsetting'),
            preserve_default=False,
        ),
    ]
